/// ISO 639-1 and ISO 639-2 language code mappings
/// Each language entry contains:
/// - name: English name of the language
/// - iso639_1: 2-letter ISO 639-1 code
/// - iso639_2: 3-letter ISO 639-2 code
/// - country_code: Primary country association in format '{language}_{COUNTRY}'
const Map<String, Map<String, String>> kLanguageCodeToLanguageMap = {
  'ab': {
    'name': 'Abkhazian',
    'iso639_1': 'ab',
    'iso639_2': 'abk',
    'country_code': 'ab_GE',
  },
  'aa': {
    'name': 'Afar',
    'iso639_1': 'aa',
    'iso639_2': 'aar',
    'country_code': 'aa_ET',
  },
  'af': {
    'name': 'Afrikaans',
    'iso639_1': 'af',
    'iso639_2': 'afr',
    'country_code': 'af_ZA',
  },
  'ak': {
    'name': 'Akan',
    'iso639_1': 'ak',
    'iso639_2': 'aka',
    'country_code': 'ak_GH',
  },
  'sq': {
    'name': 'Albanian',
    'iso639_1': 'sq',
    'iso639_2': 'alb',
    'country_code': 'sq_AL',
  },
  'am': {
    'name': 'Amharic',
    'iso639_1': 'am',
    'iso639_2': 'amh',
    'country_code': 'am_ET',
  },
  'ar': {
    'name': 'Arabic',
    'iso639_1': 'ar',
    'iso639_2': 'ara',
    'country_code': 'ar_SA',
  },
  'an': {
    'name': 'Aragonese',
    'iso639_1': 'an',
    'iso639_2': 'arg',
    'country_code': 'an_ES',
  },
  'hy': {
    'name': 'Armenian',
    'iso639_1': 'hy',
    'iso639_2': 'arm',
    'country_code': 'hy_AM',
  },
  'as': {
    'name': 'Assamese',
    'iso639_1': 'as',
    'iso639_2': 'asm',
    'country_code': 'as_IN',
  },
  'av': {
    'name': 'Avaric',
    'iso639_1': 'av',
    'iso639_2': 'ava',
    'country_code': 'av_RU',
  },
  'ae': {
    'name': 'Avestan',
    'iso639_1': 'ae',
    'iso639_2': 'ave',
    'country_code': 'ae_IR',
  },
  'ay': {
    'name': 'Aymara',
    'iso639_1': 'ay',
    'iso639_2': 'aym',
    'country_code': 'ay_BO',
  },
  'az': {
    'name': 'Azerbaijani',
    'iso639_1': 'az',
    'iso639_2': 'aze',
    'country_code': 'az_AZ',
  },
  'bm': {
    'name': 'Bambara',
    'iso639_1': 'bm',
    'iso639_2': 'bam',
    'country_code': 'bm_ML',
  },
  'ba': {
    'name': 'Bashkir',
    'iso639_1': 'ba',
    'iso639_2': 'bak',
    'country_code': 'ba_RU',
  },
  'eu': {
    'name': 'Basque',
    'iso639_1': 'eu',
    'iso639_2': 'baq',
    'country_code': 'eu_ES',
  },
  'be': {
    'name': 'Belarusian',
    'iso639_1': 'be',
    'iso639_2': 'bel',
    'country_code': 'be_BY',
  },
  'bn': {
    'name': 'Bengali',
    'iso639_1': 'bn',
    'iso639_2': 'ben',
    'country_code': 'bn_BD',
  },
  'bh': {
    'name': 'Bihari',
    'iso639_1': 'bh',
    'iso639_2': 'bih',
    'country_code': 'bh_IN',
  },
  'bi': {
    'name': 'Bislama',
    'iso639_1': 'bi',
    'iso639_2': 'bis',
    'country_code': 'bi_VU',
  },
  'bs': {
    'name': 'Bosnian',
    'iso639_1': 'bs',
    'iso639_2': 'bos',
    'country_code': 'bs_BA',
  },
  'br': {
    'name': 'Breton',
    'iso639_1': 'br',
    'iso639_2': 'bre',
    'country_code': 'br_FR',
  },
  'bg': {
    'name': 'Bulgarian',
    'iso639_1': 'bg',
    'iso639_2': 'bul',
    'country_code': 'bg_BG',
  },
  'my': {
    'name': 'Burmese',
    'iso639_1': 'my',
    'iso639_2': 'bur',
    'country_code': 'my_MM',
  },
  'ca': {
    'name': 'Catalan',
    'iso639_1': 'ca',
    'iso639_2': 'cat',
    'country_code': 'ca_ES',
  },
  'ch': {
    'name': 'Chamorro',
    'iso639_1': 'ch',
    'iso639_2': 'cha',
    'country_code': 'ch_GU',
  },
  'ce': {
    'name': 'Chechen',
    'iso639_1': 'ce',
    'iso639_2': 'che',
    'country_code': 'ce_RU',
  },
  'ny': {
    'name': 'Chichewa',
    'iso639_1': 'ny',
    'iso639_2': 'nya',
    'country_code': 'ny_MW',
  },
  'zh': {
    'name': 'Chinese',
    'iso639_1': 'zh',
    'iso639_2': 'chi',
    'country_code': 'zh_CN',
  },
  'cv': {
    'name': 'Chuvash',
    'iso639_1': 'cv',
    'iso639_2': 'chv',
    'country_code': 'cv_RU',
  },
  'kw': {
    'name': 'Cornish',
    'iso639_1': 'kw',
    'iso639_2': 'cor',
    'country_code': 'kw_GB',
  },
  'co': {
    'name': 'Corsican',
    'iso639_1': 'co',
    'iso639_2': 'cos',
    'country_code': 'co_FR',
  },
  'cr': {
    'name': 'Cree',
    'iso639_1': 'cr',
    'iso639_2': 'cre',
    'country_code': 'cr_CA',
  },
  'hr': {
    'name': 'Croatian',
    'iso639_1': 'hr',
    'iso639_2': 'hrv',
    'country_code': 'hr_HR',
  },
  'cs': {
    'name': 'Czech',
    'iso639_1': 'cs',
    'iso639_2': 'cze',
    'country_code': 'cs_CZ',
  },
  'da': {
    'name': 'Danish',
    'iso639_1': 'da',
    'iso639_2': 'dan',
    'country_code': 'da_DK',
  },
  'dv': {
    'name': 'Divehi',
    'iso639_1': 'dv',
    'iso639_2': 'div',
    'country_code': 'dv_MV',
  },
  'nl': {
    'name': 'Dutch',
    'iso639_1': 'nl',
    'iso639_2': 'dut',
    'country_code': 'nl_NL',
  },
  'dz': {
    'name': 'Dzongkha',
    'iso639_1': 'dz',
    'iso639_2': 'dzo',
    'country_code': 'dz_BT',
  },
  'en': {
    'name': 'English',
    'iso639_1': 'en',
    'iso639_2': 'eng',
    'country_code': 'en_US',
  },
  'eo': {
    'name': 'Esperanto',
    'iso639_1': 'eo',
    'iso639_2': 'epo',
    'country_code': 'eo_XX',
  },
  'et': {
    'name': 'Estonian',
    'iso639_1': 'et',
    'iso639_2': 'est',
    'country_code': 'et_EE',
  },
  'ee': {
    'name': 'Ewe',
    'iso639_1': 'ee',
    'iso639_2': 'ewe',
    'country_code': 'ee_GH',
  },
  'fo': {
    'name': 'Faroese',
    'iso639_1': 'fo',
    'iso639_2': 'fao',
    'country_code': 'fo_FO',
  },
  'fj': {
    'name': 'Fijian',
    'iso639_1': 'fj',
    'iso639_2': 'fij',
    'country_code': 'fj_FJ',
  },
  'fi': {
    'name': 'Finnish',
    'iso639_1': 'fi',
    'iso639_2': 'fin',
    'country_code': 'fi_FI',
  },
  'fr': {
    'name': 'French',
    'iso639_1': 'fr',
    'iso639_2': 'fre',
    'country_code': 'fr_FR',
  },
  'ff': {
    'name': 'Fulah',
    'iso639_1': 'ff',
    'iso639_2': 'ful',
    'country_code': 'ff_SN',
  },
  'gl': {
    'name': 'Galician',
    'iso639_1': 'gl',
    'iso639_2': 'glg',
    'country_code': 'gl_ES',
  },
  'ka': {
    'name': 'Georgian',
    'iso639_1': 'ka',
    'iso639_2': 'geo',
    'country_code': 'ka_GE',
  },
  'de': {
    'name': 'German',
    'iso639_1': 'de',
    'iso639_2': 'ger',
    'country_code': 'de_DE',
  },
  'el': {
    'name': 'Greek',
    'iso639_1': 'el',
    'iso639_2': 'gre',
    'country_code': 'el_GR',
  },
  'gn': {
    'name': 'Guaraní',
    'iso639_1': 'gn',
    'iso639_2': 'grn',
    'country_code': 'gn_PY',
  },
  'gu': {
    'name': 'Gujarati',
    'iso639_1': 'gu',
    'iso639_2': 'guj',
    'country_code': 'gu_IN',
  },
  'ht': {
    'name': 'Haitian',
    'iso639_1': 'ht',
    'iso639_2': 'hat',
    'country_code': 'ht_HT',
  },
  'ha': {
    'name': 'Hausa',
    'iso639_1': 'ha',
    'iso639_2': 'hau',
    'country_code': 'ha_NG',
  },
  'he': {
    'name': 'Hebrew',
    'iso639_1': 'he',
    'iso639_2': 'heb',
    'country_code': 'he_IL',
  },
  'hz': {
    'name': 'Herero',
    'iso639_1': 'hz',
    'iso639_2': 'her',
    'country_code': 'hz_NA',
  },
  'hi': {
    'name': 'Hindi',
    'iso639_1': 'hi',
    'iso639_2': 'hin',
    'country_code': 'hi_IN',
  },
  'ho': {
    'name': 'Hiri Motu',
    'iso639_1': 'ho',
    'iso639_2': 'hmo',
    'country_code': 'ho_PG',
  },
  'hu': {
    'name': 'Hungarian',
    'iso639_1': 'hu',
    'iso639_2': 'hun',
    'country_code': 'hu_HU',
  },
  'ia': {
    'name': 'Interlingua',
    'iso639_1': 'ia',
    'iso639_2': 'ina',
    'country_code': 'ia_XX',
  },
  'id': {
    'name': 'Indonesian',
    'iso639_1': 'id',
    'iso639_2': 'ind',
    'country_code': 'id_ID',
  },
  'ie': {
    'name': 'Interlingue',
    'iso639_1': 'ie',
    'iso639_2': 'ile',
    'country_code': 'ie_XX',
  },
  'ga': {
    'name': 'Irish',
    'iso639_1': 'ga',
    'iso639_2': 'gle',
    'country_code': 'ga_IE',
  },
  'ig': {
    'name': 'Igbo',
    'iso639_1': 'ig',
    'iso639_2': 'ibo',
    'country_code': 'ig_NG',
  },
  'ik': {
    'name': 'Inupiaq',
    'iso639_1': 'ik',
    'iso639_2': 'ipk',
    'country_code': 'ik_US',
  },
  'io': {
    'name': 'Ido',
    'iso639_1': 'io',
    'iso639_2': 'ido',
    'country_code': 'io_XX',
  },
  'is': {
    'name': 'Icelandic',
    'iso639_1': 'is',
    'iso639_2': 'ice',
    'country_code': 'is_IS',
  },
  'it': {
    'name': 'Italian',
    'iso639_1': 'it',
    'iso639_2': 'ita',
    'country_code': 'it_IT',
  },
  'iu': {
    'name': 'Inuktitut',
    'iso639_1': 'iu',
    'iso639_2': 'iku',
    'country_code': 'iu_CA',
  },
  'ja': {
    'name': 'Japanese',
    'iso639_1': 'ja',
    'iso639_2': 'jpn',
    'country_code': 'ja_JP',
  },
  'jv': {
    'name': 'Javanese',
    'iso639_1': 'jv',
    'iso639_2': 'jav',
    'country_code': 'jv_ID',
  },
  'kl': {
    'name': 'Kalaallisut',
    'iso639_1': 'kl',
    'iso639_2': 'kal',
    'country_code': 'kl_GL',
  },
  'kn': {
    'name': 'Kannada',
    'iso639_1': 'kn',
    'iso639_2': 'kan',
    'country_code': 'kn_IN',
  },
  'kr': {
    'name': 'Kanuri',
    'iso639_1': 'kr',
    'iso639_2': 'kau',
    'country_code': 'kr_NG',
  },
  'ks': {
    'name': 'Kashmiri',
    'iso639_1': 'ks',
    'iso639_2': 'kas',
    'country_code': 'ks_IN',
  },
  'kk': {
    'name': 'Kazakh',
    'iso639_1': 'kk',
    'iso639_2': 'kaz',
    'country_code': 'kk_KZ',
  },
  'km': {
    'name': 'Khmer',
    'iso639_1': 'km',
    'iso639_2': 'khm',
    'country_code': 'km_KH',
  },
  'ki': {
    'name': 'Kikuyu',
    'iso639_1': 'ki',
    'iso639_2': 'kik',
    'country_code': 'ki_KE',
  },
  'rw': {
    'name': 'Kinyarwanda',
    'iso639_1': 'rw',
    'iso639_2': 'kin',
    'country_code': 'rw_RW',
  },
  'ky': {
    'name': 'Kirghiz',
    'iso639_1': 'ky',
    'iso639_2': 'kir',
    'country_code': 'ky_KG',
  },
  'kv': {
    'name': 'Komi',
    'iso639_1': 'kv',
    'iso639_2': 'kom',
    'country_code': 'kv_RU',
  },
  'kg': {
    'name': 'Kongo',
    'iso639_1': 'kg',
    'iso639_2': 'kon',
    'country_code': 'kg_CD',
  },
  'ko': {
    'name': 'Korean',
    'iso639_1': 'ko',
    'iso639_2': 'kor',
    'country_code': 'ko_KR',
  },
  'ku': {
    'name': 'Kurdish',
    'iso639_1': 'ku',
    'iso639_2': 'kur',
    'country_code': 'ku_TR',
  },
  'kj': {
    'name': 'Kwanyama',
    'iso639_1': 'kj',
    'iso639_2': 'kua',
    'country_code': 'kj_NA',
  },
  'la': {
    'name': 'Latin',
    'iso639_1': 'la',
    'iso639_2': 'lat',
    'country_code': 'la_VA',
  },
  'lb': {
    'name': 'Luxembourgish',
    'iso639_1': 'lb',
    'iso639_2': 'ltz',
    'country_code': 'lb_LU',
  },
  'lg': {
    'name': 'Luganda',
    'iso639_1': 'lg',
    'iso639_2': 'lug',
    'country_code': 'lg_UG',
  },
  'li': {
    'name': 'Limburgish',
    'iso639_1': 'li',
    'iso639_2': 'lim',
    'country_code': 'li_NL',
  },
  'ln': {
    'name': 'Lingala',
    'iso639_1': 'ln',
    'iso639_2': 'lin',
    'country_code': 'ln_CD',
  },
  'lo': {
    'name': 'Lao',
    'iso639_1': 'lo',
    'iso639_2': 'lao',
    'country_code': 'lo_LA',
  },
  'lt': {
    'name': 'Lithuanian',
    'iso639_1': 'lt',
    'iso639_2': 'lit',
    'country_code': 'lt_LT',
  },
  'lu': {
    'name': 'Luba-Katanga',
    'iso639_1': 'lu',
    'iso639_2': 'lub',
    'country_code': 'lu_CD',
  },
  'lv': {
    'name': 'Latvian',
    'iso639_1': 'lv',
    'iso639_2': 'lav',
    'country_code': 'lv_LV',
  },
  'gv': {
    'name': 'Manx',
    'iso639_1': 'gv',
    'iso639_2': 'glv',
    'country_code': 'gv_IM',
  },
  'mk': {
    'name': 'Macedonian',
    'iso639_1': 'mk',
    'iso639_2': 'mac',
    'country_code': 'mk_MK',
  },
  'mg': {
    'name': 'Malagasy',
    'iso639_1': 'mg',
    'iso639_2': 'mlg',
    'country_code': 'mg_MG',
  },
  'ms': {
    'name': 'Malay',
    'iso639_1': 'ms',
    'iso639_2': 'may',
    'country_code': 'ms_MY',
  },
  'ml': {
    'name': 'Malayalam',
    'iso639_1': 'ml',
    'iso639_2': 'mal',
    'country_code': 'ml_IN',
  },
  'mt': {
    'name': 'Maltese',
    'iso639_1': 'mt',
    'iso639_2': 'mlt',
    'country_code': 'mt_MT',
  },
  'mi': {
    'name': 'Māori',
    'iso639_1': 'mi',
    'iso639_2': 'mao',
    'country_code': 'mi_NZ',
  },
  'mr': {
    'name': 'Marathi',
    'iso639_1': 'mr',
    'iso639_2': 'mar',
    'country_code': 'mr_IN',
  },
  'mh': {
    'name': 'Marshallese',
    'iso639_1': 'mh',
    'iso639_2': 'mah',
    'country_code': 'mh_MH',
  },
  'mn': {
    'name': 'Mongolian',
    'iso639_1': 'mn',
    'iso639_2': 'mon',
    'country_code': 'mn_MN',
  },
  'na': {
    'name': 'Nauru',
    'iso639_1': 'na',
    'iso639_2': 'nau',
    'country_code': 'na_NR',
  },
  'nv': {
    'name': 'Navajo',
    'iso639_1': 'nv',
    'iso639_2': 'nav',
    'country_code': 'nv_US',
  },
  'nb': {
    'name': 'Norwegian Bokmål',
    'iso639_1': 'nb',
    'iso639_2': 'nob',
    'country_code': 'nb_NO',
  },
  'nd': {
    'name': 'North Ndebele',
    'iso639_1': 'nd',
    'iso639_2': 'nde',
    'country_code': 'nd_ZW',
  },
  'ne': {
    'name': 'Nepali',
    'iso639_1': 'ne',
    'iso639_2': 'nep',
    'country_code': 'ne_NP',
  },
  'ng': {
    'name': 'Ndonga',
    'iso639_1': 'ng',
    'iso639_2': 'ndo',
    'country_code': 'ng_NA',
  },
  'nn': {
    'name': 'Norwegian Nynorsk',
    'iso639_1': 'nn',
    'iso639_2': 'nno',
    'country_code': 'nn_NO',
  },
  'no': {
    'name': 'Norwegian',
    'iso639_1': 'no',
    'iso639_2': 'nor',
    'country_code': 'no_NO',
  },
  'ii': {
    'name': 'Nuosu',
    'iso639_1': 'ii',
    'iso639_2': 'iii',
    'country_code': 'ii_CN',
  },
  'nr': {
    'name': 'South Ndebele',
    'iso639_1': 'nr',
    'iso639_2': 'nbl',
    'country_code': 'nr_ZA',
  },
  'oc': {
    'name': 'Occitan',
    'iso639_1': 'oc',
    'iso639_2': 'oci',
    'country_code': 'oc_FR',
  },
  'oj': {
    'name': 'Ojibwe',
    'iso639_1': 'oj',
    'iso639_2': 'oji',
    'country_code': 'oj_CA',
  },
  'cu': {
    'name': 'Old Church Slavonic',
    'iso639_1': 'cu',
    'iso639_2': 'chu',
    'country_code': 'cu_BG',
  },
  'om': {
    'name': 'Oromo',
    'iso639_1': 'om',
    'iso639_2': 'orm',
    'country_code': 'om_ET',
  },
  'or': {
    'name': 'Oriya',
    'iso639_1': 'or',
    'iso639_2': 'ori',
    'country_code': 'or_IN',
  },
  'os': {
    'name': 'Ossetian',
    'iso639_1': 'os',
    'iso639_2': 'oss',
    'country_code': 'os_RU',
  },
  'pa': {
    'name': 'Panjabi',
    'iso639_1': 'pa',
    'iso639_2': 'pan',
    'country_code': 'pa_IN',
  },
  'pi': {
    'name': 'Pāli',
    'iso639_1': 'pi',
    'iso639_2': 'pli',
    'country_code': 'pi_IN',
  },
  'fa': {
    'name': 'Persian',
    'iso639_1': 'fa',
    'iso639_2': 'per',
    'country_code': 'fa_IR',
  },
  'pl': {
    'name': 'Polish',
    'iso639_1': 'pl',
    'iso639_2': 'pol',
    'country_code': 'pl_PL',
  },
  'ps': {
    'name': 'Pashto',
    'iso639_1': 'ps',
    'iso639_2': 'pus',
    'country_code': 'ps_AF',
  },
  'pt': {
    'name': 'Portuguese',
    'iso639_1': 'pt',
    'iso639_2': 'por',
    'country_code': 'pt_PT',
  },
  'qu': {
    'name': 'Quechua',
    'iso639_1': 'qu',
    'iso639_2': 'que',
    'country_code': 'qu_PE',
  },
  'rm': {
    'name': 'Romansh',
    'iso639_1': 'rm',
    'iso639_2': 'roh',
    'country_code': 'rm_CH',
  },
  'rn': {
    'name': 'Kirundi',
    'iso639_1': 'rn',
    'iso639_2': 'run',
    'country_code': 'rn_BI',
  },
  'ro': {
    'name': 'Romanian',
    'iso639_1': 'ro',
    'iso639_2': 'rum',
    'country_code': 'ro_RO',
  },
  'ru': {
    'name': 'Russian',
    'iso639_1': 'ru',
    'iso639_2': 'rus',
    'country_code': 'ru_RU',
  },
  'sa': {
    'name': 'Sanskrit',
    'iso639_1': 'sa',
    'iso639_2': 'san',
    'country_code': 'sa_IN',
  },
  'sc': {
    'name': 'Sardinian',
    'iso639_1': 'sc',
    'iso639_2': 'srd',
    'country_code': 'sc_IT',
  },
  'sd': {
    'name': 'Sindhi',
    'iso639_1': 'sd',
    'iso639_2': 'snd',
    'country_code': 'sd_PK',
  },
  'se': {
    'name': 'Northern Sami',
    'iso639_1': 'se',
    'iso639_2': 'sme',
    'country_code': 'se_NO',
  },
  'sm': {
    'name': 'Samoan',
    'iso639_1': 'sm',
    'iso639_2': 'smo',
    'country_code': 'sm_WS',
  },
  'sg': {
    'name': 'Sango',
    'iso639_1': 'sg',
    'iso639_2': 'sag',
    'country_code': 'sg_CF',
  },
  'sr': {
    'name': 'Serbian',
    'iso639_1': 'sr',
    'iso639_2': 'srp',
    'country_code': 'sr_RS',
  },
  'gd': {
    'name': 'Scottish Gaelic',
    'iso639_1': 'gd',
    'iso639_2': 'gla',
    'country_code': 'gd_GB',
  },
  'sn': {
    'name': 'Shona',
    'iso639_1': 'sn',
    'iso639_2': 'sna',
    'country_code': 'sn_ZW',
  },
  'si': {
    'name': 'Sinhala',
    'iso639_1': 'si',
    'iso639_2': 'sin',
    'country_code': 'si_LK',
  },
  'sk': {
    'name': 'Slovak',
    'iso639_1': 'sk',
    'iso639_2': 'slo',
    'country_code': 'sk_SK',
  },
  'sl': {
    'name': 'Slovenian',
    'iso639_1': 'sl',
    'iso639_2': 'slv',
    'country_code': 'sl_SI',
  },
  'so': {
    'name': 'Somali',
    'iso639_1': 'so',
    'iso639_2': 'som',
    'country_code': 'so_SO',
  },
  'st': {
    'name': 'Southern Sotho',
    'iso639_1': 'st',
    'iso639_2': 'sot',
    'country_code': 'st_LS',
  },
  'es': {
    'name': 'Spanish',
    'iso639_1': 'es',
    'iso639_2': 'spa',
    'country_code': 'es_ES',
  },
  'su': {
    'name': 'Sundanese',
    'iso639_1': 'su',
    'iso639_2': 'sun',
    'country_code': 'su_ID',
  },
  'sw': {
    'name': 'Swahili',
    'iso639_1': 'sw',
    'iso639_2': 'swa',
    'country_code': 'sw_KE',
  },
  'ss': {
    'name': 'Swati',
    'iso639_1': 'ss',
    'iso639_2': 'ssw',
    'country_code': 'ss_SZ',
  },
  'sv': {
    'name': 'Swedish',
    'iso639_1': 'sv',
    'iso639_2': 'swe',
    'country_code': 'sv_SE',
  },
  'ta': {
    'name': 'Tamil',
    'iso639_1': 'ta',
    'iso639_2': 'tam',
    'country_code': 'ta_IN',
  },
  'te': {
    'name': 'Telugu',
    'iso639_1': 'te',
    'iso639_2': 'tel',
    'country_code': 'te_IN',
  },
  'tg': {
    'name': 'Tajik',
    'iso639_1': 'tg',
    'iso639_2': 'tgk',
    'country_code': 'tg_TJ',
  },
  'th': {
    'name': 'Thai',
    'iso639_1': 'th',
    'iso639_2': 'tha',
    'country_code': 'th_TH',
  },
  'ti': {
    'name': 'Tigrinya',
    'iso639_1': 'ti',
    'iso639_2': 'tir',
    'country_code': 'ti_ER',
  },
  'bo': {
    'name': 'Tibetan',
    'iso639_1': 'bo',
    'iso639_2': 'tib',
    'country_code': 'bo_CN',
  },
  'tk': {
    'name': 'Turkmen',
    'iso639_1': 'tk',
    'iso639_2': 'tuk',
    'country_code': 'tk_TM',
  },
  'tl': {
    'name': 'Tagalog',
    'iso639_1': 'tl',
    'iso639_2': 'tgl',
    'country_code': 'tl_PH',
  },
  'tn': {
    'name': 'Tswana',
    'iso639_1': 'tn',
    'iso639_2': 'tsn',
    'country_code': 'tn_BW',
  },
  'to': {
    'name': 'Tonga',
    'iso639_1': 'to',
    'iso639_2': 'ton',
    'country_code': 'to_TO',
  },
  'tr': {
    'name': 'Turkish',
    'iso639_1': 'tr',
    'iso639_2': 'tur',
    'country_code': 'tr_TR',
  },
  'ts': {
    'name': 'Tsonga',
    'iso639_1': 'ts',
    'iso639_2': 'tso',
    'country_code': 'ts_ZA',
  },
  'tt': {
    'name': 'Tatar',
    'iso639_1': 'tt',
    'iso639_2': 'tat',
    'country_code': 'tt_RU',
  },
  'tw': {
    'name': 'Twi',
    'iso639_1': 'tw',
    'iso639_2': 'twi',
    'country_code': 'tw_GH',
  },
  'ty': {
    'name': 'Tahitian',
    'iso639_1': 'ty',
    'iso639_2': 'tah',
    'country_code': 'ty_PF',
  },
  'ug': {
    'name': 'Uighur',
    'iso639_1': 'ug',
    'iso639_2': 'uig',
    'country_code': 'ug_CN',
  },
  'uk': {
    'name': 'Ukrainian',
    'iso639_1': 'uk',
    'iso639_2': 'ukr',
    'country_code': 'uk_UA',
  },
  'ur': {
    'name': 'Urdu',
    'iso639_1': 'ur',
    'iso639_2': 'urd',
    'country_code': 'ur_PK',
  },
  'uz': {
    'name': 'Uzbek',
    'iso639_1': 'uz',
    'iso639_2': 'uzb',
    'country_code': 'uz_UZ',
  },
  've': {
    'name': 'Venda',
    'iso639_1': 've',
    'iso639_2': 'ven',
    'country_code': 've_ZA',
  },
  'vi': {
    'name': 'Vietnamese',
    'iso639_1': 'vi',
    'iso639_2': 'vie',
    'country_code': 'vi_VN',
  },
  'vo': {
    'name': 'Volapük',
    'iso639_1': 'vo',
    'iso639_2': 'vol',
    'country_code': 'vo_XX',
  },
  'wa': {
    'name': 'Walloon',
    'iso639_1': 'wa',
    'iso639_2': 'wln',
    'country_code': 'wa_BE',
  },
  'cy': {
    'name': 'Welsh',
    'iso639_1': 'cy',
    'iso639_2': 'wel',
    'country_code': 'cy_GB',
  },
  'wo': {
    'name': 'Wolof',
    'iso639_1': 'wo',
    'iso639_2': 'wol',
    'country_code': 'wo_SN',
  },
  'fy': {
    'name': 'Western Frisian',
    'iso639_1': 'fy',
    'iso639_2': 'fry',
    'country_code': 'fy_NL',
  },
  'xh': {
    'name': 'Xhosa',
    'iso639_1': 'xh',
    'iso639_2': 'xho',
    'country_code': 'xh_ZA',
  },
  'yi': {
    'name': 'Yiddish',
    'iso639_1': 'yi',
    'iso639_2': 'yid',
    'country_code': 'yi_IL',
  },
  'yo': {
    'name': 'Yoruba',
    'iso639_1': 'yo',
    'iso639_2': 'yor',
    'country_code': 'yo_NG',
  },
  'za': {
    'name': 'Zhuang',
    'iso639_1': 'za',
    'iso639_2': 'zha',
    'country_code': 'za_CN',
  },
  'zu': {
    'name': 'Zulu',
    'iso639_1': 'zu',
    'iso639_2': 'zul',
    'country_code': 'zu_ZA',
  },
};